# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GifModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=100)),
                ('text_list', models.CharField(max_length=500)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
