# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(upload_to='my_demo_app\\static\\media\\logo')),
                ('text_list_str', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GifModel',
        ),
    ]
